name: Go 2023

on:
  push:
    branches:
      - main
    paths:
      - '2023/**'

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21

    - name: Run Tests and Benchmarks
      working-directory: ./2023
      run: go test -timeout 10s -bench=. -benchmem ./...
